language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

sudo: false

matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable
    - os: linux
      env: ATOM_CHANNEL=beta
    - os: osx
      env: ATOM_CHANNEL=stable
    - os: osx
      env: ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
